services:
  - type: web
    name: codelens-backend
    runtime: python
    repo: https://github.com/shiv-am0/CodeLens
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codelens-db
          property: connectionString
      - key: DATABASE_URL_SYNC
        fromDatabase:
          name: codelens-db
          property: connectionString
      - key: LLM_PROVIDER
        value: openai
      - key: OPENAI_CHAT_MODEL
        value: gpt-4o-mini
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: ADMIN_PASSWORD
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
    healthCheckPath: /api/health

databases:
  - name: codelens-db
    plan: free
    postgresMajorVersion: 16
